default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: instadramclone_development

test:
  <<: *default
  database: instadramclone_test

production:
  <<: *default
  database: instadramclone_production
  username: instadramclone
  password: <%= ENV['INSTADRAMCLONE_DATABASE_PASSWORD'] %>
